--- #YAML:1.0
name:               Perl-Repository-APC
version:            2.002001
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::MD5:         0
    ExtUtils::Manifest:  1.50
    File::Spec:          0
    List::Util:          0
    Module::CoreList:    2.13
    Test::More:          0
    version:             0.74
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.5502
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
